import type { Metadata } from 'next';
import ProviderSessions from '@/components/ProviderSessions';
import { Albert_Sans } from 'next/font/google';
import './globals.css';
import React, { ReactNode } from 'react';
import Header from '@/components/Header';

const albertSans = Albert_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang='en'>
      <body className={albertSans.className}>
        <ProviderSessions>
          <Header />
          {children}
        </ProviderSessions>
      </body>
    </html>
  );
}
