import { AppProps } from 'next/app';
import type { Metadata } from 'next';
import ProviderSessions from '@/components/ProviderSessions';
import { Inter } from 'next/font/google';
import './globals.css';
import React, { ReactNode } from 'react';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ProviderSessions>
          <Header />
          {children}
        </ProviderSessions>
      </body>
    </html>
  );
}
